// Design-system principle 1: tokens, not values. Component stylesheets, including <style>
// blocks in .astro files, may not contain raw colours, lengths or timings; only the token and
// font files may. See .claude/skills/acme-design-system.
export default {
  extends: ["stylelint-config-standard"],
  plugins: ["stylelint-declaration-strict-value"],
  // Generated byte-for-byte copies are never edited here, so they are not linted here.
  ignoreFiles: [
    "src/styles/tokens.css",
    "src/styles/fonts.fallback.css",
    ".claude/**",
    "dist/**",
    "node_modules/**",
  ],
  rules: {
    "scale-unlimited/declaration-strict-value": [
      [
        // Every colour-bearing property except color-scheme, whose values are keywords.
        "/^(?!color-scheme$)(.*-)?color$/",
        "background",
        "background-image",
        "border",
        "border-top",
        "border-right",
        "border-bottom",
        "border-left",
        "/^border(-(top|right|bottom|left|inline|block))?-(width|style)$/",
        "fill",
        "stroke",
        "box-shadow",
        "text-shadow",
        "outline",
        "outline-offset",
        "outline-width",
        // Spacing and size, including longhands and logical properties.
        "/^(margin|padding|inset|scroll-margin|scroll-padding)(-(top|right|bottom|left|inline|block|inline-start|inline-end|block-start|block-end))?$/",
        "/^(width|height|min-width|max-width|min-height|max-height|inline-size|block-size|min-inline-size|max-inline-size|flex-basis)$/",
        "/^(top|right|bottom|left|gap|row-gap|column-gap)$/",
        "font-size",
        "font-family",
        "font-weight",
        "line-height",
        "letter-spacing",
        "border-radius",
        "transition",
        "transition-duration",
        "transition-timing-function",
        "animation",
        "animation-duration",
        "animation-timing-function",
      ],
      {
        ignoreValues: [
          "0",
          "auto",
          "none",
          "inherit",
          "initial",
          "unset",
          "revert",
          "currentColor",
          "currentcolor",
          "transparent",
          "100%",
          "100vh",
          "100dvh",
          "1",
          "1.5",
          "normal",
          "bold",
          "solid",
        ],
        disableFix: true,
      },
    ],
    // Class names mirror Figma variants (btn--primary, badge__label), which the standard pattern rejects.
    "selector-class-pattern": null,
    "custom-property-pattern": null,
  },
  overrides: [
    {
      files: ["src/styles/tokens.site.css", "src/styles/fonts.css"],
      rules: {
        "scale-unlimited/declaration-strict-value": null,
      },
    },
    {
      files: ["**/*.astro"],
      customSyntax: "postcss-html",
    },
  ],
};
