// One source for the response headers the Worker serves with the static assets.
// scripts/build-headers.mjs renders this into dist/_headers with the hash of the theme
// bootstrap, the only inline script; a fallback Worker for the résumé route would import the
// same object. Values follow the web-quality skill: a CSP of self plus that hash and no
// unsafe-inline (same-origin connections allowed, nothing else), HSTS with preload, nosniff, a
// strict referrer policy, camera, microphone and geolocation denied, framing denied. The CSP
// is detached on the PDF paths so browser PDF viewers are unaffected and the file is served
// inline, and fingerprinted assets are cached for a year.

/**
 * Every workers.dev host is a preview (production is the custom domain only) and must never be
 * indexed. A placeholder stops at a dot, so this matches the preview Worker's own host and the
 * version preview hosts, which prefix the Worker name inside the first label.
 */
export const previewHost = ":worker.:subdomain.workers.dev";

export function contentSecurityPolicy(scriptHash) {
  return [
    "default-src 'none'",
    `script-src 'self' '${scriptHash}'`,
    "style-src 'self'",
    "font-src 'self'",
    "img-src 'self'",
    // Same-origin fetches only. The site makes none, but Lighthouse reads robots.txt from the
    // page, and without this the SEO gate fails on a policy that is otherwise correct.
    "connect-src 'self'",
    "base-uri 'none'",
    "form-action 'none'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
  ].join("; ");
}

export function securityHeaders(scriptHash) {
  return {
    "Content-Security-Policy": contentSecurityPolicy(scriptHash),
    "Strict-Transport-Security": "max-age=63072000; includeSubDomains; preload",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(), microphone=(), geolocation=()",
    "X-Frame-Options": "DENY",
  };
}

/**
 * The _headers file. `pdfPaths` are every path that serves the résumé (the file and its proxy
 * route); `filename` names the download.
 */
export function renderHeaders({ scriptHash, pdfPaths, filename }) {
  const block = (path, lines) => [path, ...lines.map((l) => `  ${l}`)].join("\n");
  const pdfRules = pdfPaths.map((path) =>
    block(path, [
      "! Content-Security-Policy",
      `Content-Disposition: inline; filename="${filename}"`,
    ]),
  );
  return [
    "# GENERATED by scripts/build-headers.mjs from src/config/headers.mjs at build. Not committed.",
    block(
      "/*",
      Object.entries(securityHeaders(scriptHash)).map(([name, value]) => `${name}: ${value}`),
    ),
    block("/_astro/*", ["Cache-Control: public, max-age=31536000, immutable"]),
    ...pdfRules,
    block(`https://${previewHost}/*`, ["X-Robots-Tag: noindex, nofollow"]),
    "",
  ].join("\n");
}
