// Copies the design system token sheet from the skill into the site, or checks that the copy
// is byte-identical. The skill is the source of truth; src/styles/tokens.css is generated.
//   node scripts/sync-tokens.mjs          write the copy
//   node scripts/sync-tokens.mjs --check  exit 1 if the copy is missing or differs
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const source = resolve(root, ".claude/skills/acme-design-system/tokens.css");
const target = resolve(root, "src/styles/tokens.css");
const check = process.argv.includes("--check");

const banner =
  "/* GENERATED by scripts/sync-tokens.mjs from .claude/skills/acme-design-system/tokens.css.\n" +
  "   Do not edit. Change the skill's sheet, then run `pnpm sync:tokens`. */\n";

const expected = banner + readFileSync(source, "utf8").replace(/\r\n/g, "\n");

if (check) {
  const actual = existsSync(target) ? readFileSync(target, "utf8").replace(/\r\n/g, "\n") : null;
  if (actual !== expected) {
    console.error(
      `src/styles/tokens.css is ${actual === null ? "missing" : "out of date"}. Run: pnpm sync:tokens`,
    );
    process.exit(1);
  }
  console.log("tokens.css is in sync with the design system skill.");
  process.exit(0);
}

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, expected, "utf8");
console.log(`Wrote ${target}`);
